### ISSUE TITLE
Add buttons as allowed inner block

### ISSUE THREAD

**Issue by helgatheviking** [DLXPlugins/alerts-dlx#2]
Hi Ron! I was just trying to create a notice and include a button but found it wasn't possible. Would you be open to expanding the list of allowed innerblocks? (I was using the chakra notice)

**Comment by helgatheviking** [comment]
Welp... opened this a bit too quickly. I found the button setting in the sidebar :)

**Comment by ronalfy** [comment]
It is a bit hidden. Any suggestions on making it more discoverable?

**Comment by helgatheviking** [comment]
Should it perhaps be on by default? And/or it might still make sense to allow innerBlocks beyond the paragraph?
